### ISSUE TITLE
Recovered column showing zero value

### ISSUE THREAD

**Issue by ppmaluch** [kenriortega/covid-resume-cuba#1]
Recovered column on Estados Unidos row from Resumen Mundial table si showing a zero value.
![Screenshot_2021-02-01-08-00-45-923_com android chrome](https://user-images.githubusercontent.com/65309755/106462261-d8657600-6463-11eb-9c0f-3401029d9655.jpg)

**Comment by kenriortega** [comment]
that is not an error, becouse the source API from covidCubadata throw this number in the request.
